# Generated by Django 4.0.2 on 2022-02-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bid_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
