# Generated by Django 4.0.2 on 2022-02-15 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_comment_name_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parrent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.comment'),
        ),
    ]
